name: Build and cache NixOS system

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          install_url: https://releases.nixos.org/nix/nix-2.18.1/install

      - name: Set up Cachix
        uses: cachix/cachix-action@v12
        with:
          name: ${{ secrets.zgabrielr }}
          authToken: ${{ secrets.eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJmYjRkNTg4ZS03OTNiLTRjMzItODA2NS02Y2ZlOGEzY> }}

      - name: Build NixOS config
        run: |
          nix build .#nixosConfigurations.myhost.config.system.build.toplevel

      - name: Upload system as artifact (optional)
        uses: actions/upload-artifact@v3
        with:
          name: nixos-result
          path: result/
